/*
 * This file was automatically generated by EvoSuite
 * Sun Dec 05 16:47:45 PST 2021
 */

package p2;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class InvalidHeaderException_ESTest extends InvalidHeaderException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidHeaderException invalidHeaderException0 = new InvalidHeaderException("");
      assertEquals("", invalidHeaderException0.getMessage());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InvalidHeaderException invalidHeaderException0 = new InvalidHeaderException();
      assertNull(invalidHeaderException0.getMessage());
  }
}
